name: Build API Doc
description: Build API Doc

runs:
  using: "composite"
  steps:
    - run: |
        poetry run nb-autodoc nonebot
        cp -r ./build/nonebot/* ./website/docs/api/
        yarn prettier
      shell: bash
