version: "3"  # docker-compose版本
services:
  docker-python-demo:  # docker-compose编排名称，一般同微服务名称，注意不要与其>他服务重名
    image: "python:3.10"  # docker镜像名及版本
    hostname: docker-nonebot  # docker容器主机名
    container_name: nonebot  # docker容器名
    volumes:  # 挂载目录
      - /home/pycharm_project/ymProject:/home/pycharm_project/ymProject  # 项目相关
      - ../docker:/docker  # docker相关
    ports:  # 端口映射
      - "8080:8080"
    environment:  # 配置环境变量
      - TZ=Asia/Shanghai  # 设置时区
    command: cd /home/pycharm_project/ymProject && python bot.py &  # 设置启动命令
    network_mode: bridge  # 网络模式：host、bridge、none等，我们使用bridge

